#!/usr/bin/env bash
set -euo pipefail

# ─── Colors ───
BOLD='\033[1m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERR ]${NC} $*"; }

REPO="lingshichat/Arona_WebUI"

# ─── Detect install directory ───
if [ -f "./package.json" ] && grep -q '"openclaw-mvp"' ./package.json 2>/dev/null; then
  INSTALL_DIR="$(cd . && pwd)"
  SKIP_DOWNLOAD=true
else
  INSTALL_DIR="${ARONA_HOME:-$HOME/.arona-webui}"
  SKIP_DOWNLOAD=false
fi

# ─── Check Node.js ───
check_node() {
  if ! command -v node &>/dev/null; then
    err "Node.js is not installed."
    echo ""
    echo "  macOS:   brew install node"
    echo "  Ubuntu:  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt install -y nodejs"
    echo "  Windows: https://nodejs.org/"
    echo ""
    exit 1
  fi

  local version
  version=$(node -v | sed 's/^v//' | cut -d. -f1)
  if [ "$version" -lt 18 ]; then
    err "Node.js >= 18 required (found $(node -v))"
    exit 1
  fi

  ok "Node.js $(node -v)"
}

# ─── Install / update code ───
install_code() {
  if [ "$SKIP_DOWNLOAD" = true ]; then
    info "Using existing project at $INSTALL_DIR"
    cd "$INSTALL_DIR"
    return
  fi

  if ! command -v curl &>/dev/null; then
    err "curl is required. Please install curl first."
    exit 1
  fi

  info "Fetching latest release from GitHub..."
  local release_url
  release_url=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | grep '"browser_download_url".*\.tar\.gz"' | head -1 | cut -d'"' -f4)

  if [ -z "$release_url" ]; then
    err "Could not find a release package. Check https://github.com/${REPO}/releases"
    exit 1
  fi

  local tmpdir
  tmpdir=$(mktemp -d)
  info "Downloading $release_url ..."
  curl -fSL "$release_url" | tar xz -C "$tmpdir"

  # The archive extracts as arona-webui-vX.Y.Z/
  local extracted
  extracted=$(ls -d "$tmpdir"/arona-webui-* 2>/dev/null | head -1)
  if [ -z "$extracted" ]; then
    err "Unexpected archive structure."
    rm -rf "$tmpdir"
    exit 1
  fi

  mkdir -p "$INSTALL_DIR"
  # Copy new files over (preserves .env.local if upgrading)
  rsync -a --exclude '.env.local' "$extracted/" "$INSTALL_DIR/" 2>/dev/null \
    || cp -a "$extracted/." "$INSTALL_DIR/"
  rm -rf "$tmpdir"

  cd "$INSTALL_DIR"
  chmod +x start.sh 2>/dev/null || true
  ok "Installed to $INSTALL_DIR"
}

# ─── Interactive configuration ───
configure() {
  echo ""
  echo -e "${BOLD}--- Configuration ---${NC}"
  echo ""

  read -rp "Gateway WebSocket URL [ws://127.0.0.1:18789]: " gw_url
  gw_url="${gw_url:-ws://127.0.0.1:18789}"

  echo ""
  echo "  Authentication mode:"
  echo "    1) Password"
  echo "    2) Token"
  echo "    3) None"
  read -rp "  Choose [1]: " auth_choice
  auth_choice="${auth_choice:-1}"

  local auth_mode="" credential=""
  case "$auth_choice" in
    2) auth_mode="token"
       read -rsp "  Gateway token: " credential; echo ;;
    3) auth_mode="none" ;;
    *) auth_mode="password"
       read -rsp "  Gateway password: " credential; echo ;;
  esac

  echo ""
  read -rp "WebUI admin username [admin]: " username
  username="${username:-admin}"

  read -rp "WebUI port [18790]: " port
  port="${port:-18790}"

  # Write .env.local
  local env_file="$INSTALL_DIR/.env.local"
  cat > "$env_file" << EOF
# Arona WebUI Configuration
# Generated by install.sh

GATEWAY_URL=$gw_url
GATEWAY_USERNAME=$username
PORT=$port
GATEWAY_ORIGIN=http://localhost:$port
EOF

  if [ "$auth_mode" = "password" ] && [ -n "$credential" ]; then
    echo "GATEWAY_PASSWORD=$credential" >> "$env_file"
  elif [ "$auth_mode" = "token" ] && [ -n "$credential" ]; then
    echo "GATEWAY_TOKEN=$credential" >> "$env_file"
  fi

  ok "Configuration saved to .env.local"
}

# ─── Test gateway connection ───
test_connection() {
  echo ""
  read -rp "Test gateway connection now? [Y/n]: " choice
  if [[ "$choice" =~ ^[Nn] ]]; then
    return 1
  fi

  info "Testing connection..."

  # Write temp CommonJS helper (project uses ESM)
  cat > "$INSTALL_DIR/_test_gw.cjs" << 'HELPER'
const { WebSocket } = require("ws");
const fs = require("fs");
const lines = fs.readFileSync(".env.local", "utf8").split("\n");
const cfg = {};
for (const l of lines) {
  const eq = l.indexOf("=");
  if (eq < 1 || l.startsWith("#")) continue;
  cfg[l.slice(0, eq).trim()] = l.slice(eq + 1).trim();
}
const ws = new WebSocket(cfg.GATEWAY_URL || "ws://127.0.0.1:18789", {
  origin: cfg.GATEWAY_ORIGIN || "http://localhost:18790"
});
const timeout = setTimeout(() => { process.stderr.write("TIMEOUT\n"); process.exit(1); }, 5000);
ws.on("open", () => {
  const auth = {};
  if (cfg.GATEWAY_PASSWORD) auth.password = cfg.GATEWAY_PASSWORD;
  if (cfg.GATEWAY_TOKEN) auth.token = cfg.GATEWAY_TOKEN;
  const params = {
    minProtocol: 3, maxProtocol: 3,
    client: { id: "install-test", version: "1.0", platform: process.platform, mode: "ui" },
    role: "operator", scopes: ["operator.read"]
  };
  if (Object.keys(auth).length > 0) params.auth = auth;
  ws.send(JSON.stringify({ type: "req", id: "1", method: "connect", params }));
});
ws.on("message", (raw) => {
  const msg = JSON.parse(raw.toString());
  if (msg.type === "event" && msg.event === "connect.challenge") {
    ws.send(JSON.stringify({ type: "req", id: "1", method: "connect", params: {
      minProtocol: 3, maxProtocol: 3,
      client: { id: "install-test" }, role: "operator", scopes: ["operator.read"]
    }}));
    return;
  }
  if (msg.type === "res") {
    clearTimeout(timeout);
    if (msg.ok) { process.stdout.write("OK\n"); ws.close(); }
    else { process.stderr.write((msg.error?.message || "auth failed") + "\n"); ws.close(); process.exit(1); }
  }
});
ws.on("error", (e) => { clearTimeout(timeout); process.stderr.write(e.message + "\n"); process.exit(1); });
HELPER

  local result
  if result=$(cd "$INSTALL_DIR" && node _test_gw.cjs 2>&1); then
    rm -f "$INSTALL_DIR/_test_gw.cjs"
    ok "Gateway connection successful!"
    return 0
  else
    rm -f "$INSTALL_DIR/_test_gw.cjs"
    warn "Connection failed: $result"
    return 1
  fi
}

# ─── Patch gateway configuration ───
patch_gateway() {
  echo ""
  read -rp "Configure gateway for WebUI access? (bind + allowedOrigins + disableDeviceAuth) [Y/n]: " choice
  if [[ "$choice" =~ ^[Nn] ]]; then return; fi

  echo ""
  echo "  Bind mode:"
  echo "    1) Loopback only (127.0.0.1)"
  echo "    2) LAN access (0.0.0.0)"
  read -rp "  Choose [1]: " bind_choice
  local bind_addr="127.0.0.1"
  [ "${bind_choice:-1}" = "2" ] && bind_addr="0.0.0.0"

  local port_val
  port_val=$(grep '^PORT=' "$INSTALL_DIR/.env.local" 2>/dev/null | cut -d= -f2 || echo "18790")
  port_val="${port_val:-18790}"

  info "Patching gateway configuration..."

  cat > "$INSTALL_DIR/_patch_gw.cjs" << HELPER
const { WebSocket } = require("ws");
const fs = require("fs");
const lines = fs.readFileSync(".env.local", "utf8").split("\\n");
const cfg = {};
for (const l of lines) {
  const eq = l.indexOf("=");
  if (eq < 1 || l.startsWith("#")) continue;
  cfg[l.slice(0, eq).trim()] = l.slice(eq + 1).trim();
}
const ws = new WebSocket(cfg.GATEWAY_URL || "ws://127.0.0.1:18789", {
  origin: cfg.GATEWAY_ORIGIN || "http://localhost:18790"
});
const timeout = setTimeout(() => { process.stderr.write("Timeout\\n"); process.exit(1); }, 10000);
let connected = false;
function sendConnect() {
  const auth = {};
  if (cfg.GATEWAY_PASSWORD) auth.password = cfg.GATEWAY_PASSWORD;
  if (cfg.GATEWAY_TOKEN) auth.token = cfg.GATEWAY_TOKEN;
  const params = {
    minProtocol: 3, maxProtocol: 3,
    client: { id: "install-patch", version: "1.0", platform: process.platform, mode: "ui" },
    role: "operator", scopes: ["operator.read", "operator.write", "operator.admin"]
  };
  if (Object.keys(auth).length > 0) params.auth = auth;
  ws.send(JSON.stringify({ type: "req", id: "connect", method: "connect", params }));
}
ws.on("open", sendConnect);
ws.on("message", (raw) => {
  const msg = JSON.parse(raw.toString());
  if (msg.type === "event" && msg.event === "connect.challenge") { sendConnect(); return; }
  if (!connected && msg.type === "res" && msg.ok && msg.id === "connect") {
    connected = true;
    ws.send(JSON.stringify({ type: "req", id: "get-cfg", method: "config.get", params: {} }));
    return;
  }
  if (msg.id === "get-cfg" && msg.ok) {
    const patch = {
      gateway: {
        bind: "${bind_addr}",
        controlUi: {
          allowedOrigins: ["http://localhost:${port_val}", "http://127.0.0.1:${port_val}"],
          dangerouslyDisableDeviceAuth: true
        }
      }
    };
    ws.send(JSON.stringify({
      type: "req", id: "patch", method: "config.patch",
      params: { raw: JSON.stringify(patch, null, 2), baseHash: msg.payload?.hash, note: "Arona install.sh: gateway config" }
    }));
    return;
  }
  if (msg.id === "patch") {
    clearTimeout(timeout);
    if (msg.ok) process.stdout.write("OK\\n");
    else process.stderr.write((msg.error?.message || "patch failed") + "\\n");
    ws.close();
    process.exit(msg.ok ? 0 : 1);
  }
});
ws.on("error", (e) => { clearTimeout(timeout); process.stderr.write(e.message + "\\n"); process.exit(1); });
HELPER

  if cd "$INSTALL_DIR" && node _patch_gw.cjs 2>&1; then
    rm -f "$INSTALL_DIR/_patch_gw.cjs"
    ok "Gateway configuration updated"
  else
    rm -f "$INSTALL_DIR/_patch_gw.cjs"
    warn "Gateway patch failed (you can configure via Setup Wizard later)"
  fi
}

# ─── Show startup instructions ───
show_startup() {
  local port_val
  port_val=$(grep '^PORT=' "$INSTALL_DIR/.env.local" 2>/dev/null | cut -d= -f2 || echo "18790")
  port_val="${port_val:-18790}"

  echo ""
  echo -e "${BOLD}========================================${NC}"
  echo -e "${BOLD}  Installation Complete!${NC}"
  echo -e "${BOLD}========================================${NC}"
  echo ""
  echo "Start Arona WebUI:"
  echo -e "  ${CYAN}cd $INSTALL_DIR && ./start.sh${NC}"
  echo ""
  echo "Or use pm2 (recommended for production):"
  echo -e "  ${CYAN}npm install -g pm2${NC}"
  echo -e "  ${CYAN}cd $INSTALL_DIR && pm2 start src/server.mjs --name arona-webui${NC}"
  echo ""
  echo "Or create a systemd service:"
  echo -e "  ${CYAN}sudo tee /etc/systemd/system/arona-webui.service > /dev/null << UNIT"
  echo "[Unit]"
  echo "Description=Arona WebUI"
  echo "After=network.target"
  echo ""
  echo "[Service]"
  echo "Type=simple"
  echo "User=$USER"
  echo "WorkingDirectory=$INSTALL_DIR"
  echo "ExecStart=$(command -v node) src/server.mjs"
  echo "Restart=on-failure"
  echo ""
  echo "[Install]"
  echo "WantedBy=multi-user.target"
  echo -e "UNIT${NC}"
  echo ""
  echo -e "  ${CYAN}sudo systemctl enable --now arona-webui${NC}"
  echo ""
  echo -e "WebUI:        ${BOLD}http://localhost:${port_val}${NC}"
  echo -e "Setup Wizard: ${BOLD}http://localhost:${port_val}/setup.html${NC}"
  echo ""
}

# ─── Main ───
main() {
  echo ""
  echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
  echo -e "${BOLD}║         Arona WebUI Installer            ║${NC}"
  echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
  echo ""

  check_node
  install_code
  configure

  if test_connection; then
    patch_gateway
  fi

  show_startup
}

main "$@"
